### ISSUE TITLE
Kanban PR Dashboard

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/kanbanbot#19]
# New Kanban - PR Dashboard

# Overview

The new Kanban to help mainly Tribe Open Source of PrestaShop Corp and also external committers and maintainers to optimize the review will be composed of the column:

- Next priority
- Waiting for author
- Waiting for PM/UX/Dev
- Ready for review
- Need second approval
- To be tested
- To be merged

Dev, QA and PM will have to navigate in the ‘PR Dashboard’ depending on their role & mission.

We call it kanban ‘PR Dashbord’ but if a member of PrestaShopCorp OS tribe submits a PR that does not match a Working Group, it’ll go there.

PR = Pull Request

LIFO = Last In, First Out
FIFO = First In, First Out

[Link to maintainer guide](https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

For some Pull Requests where a column is not relevant, the column can be skipped (documentation PRs do not need to be tested).

# Columns behavior

## **Next priority**
Next priority behavior is defined in this issue: 
~~- [ ] [Kanban PR Dashboard - Next priority#31450](https://github.com/PrestaShop/PrestaShop/issues/31450)~~

## **Ready for review**
Ready for review behavior is descriped in this issue:
~~- [ ] [Kanban PR Dashboard - Ready for review column behavior#31451](https://github.com/PrestaShop/PrestaShop/issues/31451)~~

## Waiting for author

Behavior described here :
- [x] https://github.com/PrestaShop/PrestaShop/issues/31457
- [x] [Kanban PR Dashboard - Enter column waiting for author with label](https://github.com/PrestaShop/PrestaShop/issues/32628)
- [ ] https://github.com/orgs/PrestaShop/projects/7/views/29?pane=issue&itemId=28643999

### How Pull Requests enter this WFPMUXDev column

Behavior described here :
- [x] [Kanban PR Dashboard - Waiting for UX PM DEV#31458](https://github.com/PrestaShop/PrestaShop/issues/31458)

### How Pull Requests exit this column (not automatic)

Dev look at ‘Waiting for dev’ PRs, PM look at ‘Waiting for PM’ PRs, UX look at ‘Waiting for UX’ PRs

When the problem is solved, PR can be moved to columns and label Waiting for PM/UX/Dev can be removed

- Waiting for Author if the author needs to change something in the PR
- Ready for Review if the PR came from this column
- To be tested if the PR came from this column
- PR can even be merged if the Waiting for UX/PM/Dev was a request for confirmation

### How Pull Requests enter this column

Expected behavior descriped below
- [x] https://github.com/PrestaShop/PrestaShop/issues/31452

### How Pull Requests exit this column

- During review, developer finds an issue!
    - If the PR has a problem, follow below _How Pull Requests enter this WFA column_
    - If however a UX/PM/Dev is needed, follow below _How Pull Requests enter this WFPMUXDev column_
- If review however is successful, the PR has the 2nd approval!
    - If PR needs to be tested, PR moves to ‘To be tested’ (and bot should add the WFQA label)
    - If PR does not need to be tested, it can be merged (and bot will take it out from the Kanban)

### How Pull Requests enter this column
- [x] [Kanban PR Dashboard - Enter column to be tested#32629](https://github.com/PrestaShop/PrestaShop/issues/32629)

### How Pull Requests exit this column

- During review, QA analyst finds an issue!
    - If the PR has a problem, follow below _How Pull Requests enter this WFA column_
    - If however a UX/PM/Dev is needed, follow below _How Pull Requests enter this WFPMUXDev column_
- If the test is successful, PR can go to column ‘To be merged’

### How Pull Requests enter this column

*PRs that do not need to be tested can enter this column when review step is successfull.*

*Else PRs enter this column when QA analyst validates it.*

*PRs in this column must be merged by maintainers.*

### How Pull Requests exit this column

- PRs exit this column when they are merged.

### Take into account other modules
- [ ] [Take into account all modules in PR Dashboard#33219](https://github.com/PrestaShop/PrestaShop/issues/33219)

*Make sure labels are the same between modules before adding them.*

### Healthcheck
- [ ] [Implement healthcheck for PR Dashboard
](https://github.com/PrestaShop/PrestaShop/issues/33218)
